### ISSUE TITLE
ver2

### ISSUE THREAD

**Issue by ideainqu** [front-end-weekend/project_weekend#9]

**Comment by Zero-1016** [comment]
문제가 있네요

**Comment by Zero-1016** [comment]
![246AAD34586CB03705](https://user-images.githubusercontent.com/115636461/222461861-22a0fa0d-0f2a-4521-b8eb-2925a8c85843.png)

**Comment by ideainqu** [comment]
> 문제가 있네요

무슨 문제 인가요? 새로운 단독 파일을 올리고 기존 파일을 다운로드 받아서 추가하고 push하지 않아서 인가요?
